### PR TITLE
process doc-files correctly

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

The `doc-files` processing was a little messed up in this component.  After reading about the `maven-javadoc-plugin`, I think this is the proper cleanup.  We can now create the proper javadoc with the `doc-files` directory in the proper location.  This PR is an alternate version of @hussainnm's PR #90 (which I could not get to work).

I also cleaned up the README to tell users how to generate the javadoc jar file (vs the javadoc apidocs directory).

### CODE REVIEW

**Comment by kwsutter** [comment]
In addition to this, I will also need to modify our Jenkins job so that the proper license text is put in place for either an EPL or EFSL build.  That's an inline job, so I will just need to directly modify that script.

**Review by hussainnm — APPROVED** [review]
This looks good. 

@kwsutter I have raised a PR https://github.com/kwsutter/jakartaee-api/pull/1 against your repo with one improvement to select the license via properties instead of depending on Jenkins script.

**Review by kazumura — APPROVED** [review]
LGTM. Thanks.

**Comment by kwsutter** [comment]
Thanks for the reviews!  @hussainnm, I also appreciate the PR for selecting the license via a build property (vs the build script).  I have commented on the PR why I won't be including that change at this juncture.  But, I definitely want to look at this type of improvement after Jakarta EE 9.

**Pull request merged**
