### PR TITLE
update pom version to 9.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

Prep for the Jakarta EE API 9.0.0 release...

### CODE REVIEW

**Comment by kwsutter** [comment]
@bshannon, here's the PR that I think should be merged instead of PR #50 (which was based off of the 8.0.0-BRANCH).

**Comment by kwsutter** [comment]
@bshannon, since you approved this PR, does that mean that we can close out PR #50 and the corresponding Issue #42?  Thanks!  I just want to ensure that we're on the same page.

**Comment by bshannon** [comment]
I'm probably losing track of which PR is for what.

PR#50 moved us to 8.0.1-SNAPSHOT, which would be needed if we needed to do a maintenance
release of the API jar files.  I seem to remember some errors in the API jar files that might
justify a maintenance release, but I haven't kept track of where we are with those.

If we need to do a maintenance release, we can either do it in master, and then when that's
done move master on to 9.0.0.  Or, we can create a branch for the maintenance release and
do it there, and move master to 9.0.0-SNAPSHOT immediately.  Your choice.  Whatever the
plan is, write it up and send it to the dev list.

**Comment by kwsutter** [comment]
Thanks, @bshannon.  I will go ahead with this merge.  Since we already have a tag for the 8.0.0 release, if we need to do a maintenance release, we can create a branch at that point and move forward.  I'll send this out to the Platform discussion as well.

**Pull request merged**
