### PR TITLE
Fix license in javadoc footer

### PR DESCRIPTION
**Pull request by hussainnm**
Set the javadocDirectory property to root folder to copy doc-files folder

### CODE REVIEW

**Comment by kwsutter** [comment]
This doesn't quite do the trick, @hussainnm.  Although it does seem to access the `doc-files` directory, the creation of the javadoc files and jar file error off...

Normal creation of javadoc in the `target/site` directory:  mvn clean install -Pstaging javadoc:javadoc
Creation of the javadoc jar file in the `target` directory:  mvn clean install -Pstaging javadoc:jar

I've been experimenting with this \<javadocDirectory> and the associated \<docfilessubdirs> options, but have not come up with the proper combination.  Maybe you have some more insights?

**Comment by kwsutter** [comment]
FYI, the `javadoc:javadoc` goal was creating the proper output with the appropriate top-level files, along with the fully populated `jakarta` directory and the `doc-files` directory -- prior to any of the proposed changes via this PR.

But, as I was creating the artifacts for the Jakarta EE 9 javadoc, I noticed that the `doc-files` directory was missing from the generated `.jar` file.

Also, as an FYI, the proposed change was referencing the `${project.basedir}` directory. But, since each of the javadocs are created by traversing to each of the subdirectories, the complete reference would need to be something like `${project.basedir}/..` or `${project.basedir}/../doc-files`.  But, of course, neither of those quite did the trick either...  More experimenting required...

**Comment by kwsutter** [comment]
With a bit more reading and experimenting, I think I have something that works...  I'll probably create my own PR and ask for your review, @hussainnm.

**Review by kwsutter — CHANGES_REQUESTED** [review]
This was a bit more involved than this PR suggested... I think I have a working version now.  @hussainnm, can you take a look at PR #91 instead of this one?  Thanks!

**Comment by hussainnm** [comment]
I will close this request

**Pull request closed without merging**
