### PR TITLE
rename GAV to jakarta.*

### LINKED ISSUE #1: Property names should be unified
In the parent pom, some properties start with ‘javax’, some with ‘jakarta’ - it would probably make sense to change those related to ‘jakarta’ artifacts to have relevant prefix

### PR DESCRIPTION
**Pull request by rieonke**
fix #1 #2

### CODE REVIEW

**Comment by rieonke** [comment]
@keilw @bshannon 
Thanks for your reminder.
Kindly let me know if there is any problem.

**Comment by romain-grecourt** [comment]
The changes to use jakarta.batch-api is AOK.
Also, I'd say the name of the properties should be mapped to the artifactId (thus package name), not the specification name.

**Comment by keilw** [comment]
Well for the spec formerly called JMS everything but the package name will change with Jakarta EE 8: https://github.com/eclipse-ee4j/jms-api/issues/221

**Comment by bshannon** [comment]
Ok, it's time to consider this, but sadly it's now out of date.
If you can update it to resolve the conflicts and to synchronize
with the new specification names [here](https://docs.google.com/spreadsheets/d/18SraPxRBCOyaS6w-UV6TR-UA1bWy1--sV0ky6msAjWY/edit#gid=0), that would be great!

Thanks!

**Comment by rieonke** [comment]
@bshannon I have checked the github repos and maven central staging repo, then updated the groupIds and artifactIds. now they are synchronized with the latest maven central staging repo.
And the output jar kept same with previous built.

**Pull request merged**
